config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  resources :friends
  root "friends#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
  validates_presence_of :firstname, :secondname, :email, :phone, :twitter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :destroy, :update, :edit]


  def index
    @friend = Friend.all  
    # aqui eu to pegando todos
  end

  def show
    # aqui eu to só criando o metodo pra poder criar uma pagina show.html.erb na view
    # @friend = Friend.find(params[:id]) é como se tivesse isso aqui
    # o set_friend ali de baixo ta fazendo a mao de passar o id aqui
  end

  def set_friend
    @friend = Friend.find(params[:id])
    # aqui eu to achando o id de cada elemento clicado e dai isso automaticamente é passado pra os outros metodos
  end

  def destroy
    @friend.destroy
    redirect_to root_path, notice: 'post apagado'
  end


  def create
    @friend= Friend.new(friend_params)
    if @friend.save
      redirect_to root_path, notice: 'friend create'
    else 
      redirect_to root_path, notice: 'error to create friend'
    end
  end

  
  def new
    @friend = Friend.new
  end

  def edit
    
  end

  def update 
    @friend.update(friend_params)
    redirect_to root_path, notice: 'atualizado'
  end

    
  def friend_params
    params.require(:friend).permit(:firstname, :secondname, :email, :phone, :twitter)
    # aqui eu to pegando os valores do input
  end






end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friend_helper.rb
module FriendHelper
end

app/views/friends/_form_partial.html.erb
<div class="container-new-friend">
<h2> Editing Friend</h2> 
<%= form_with model: friend do |form| %>
  <div>
    <%= form.text_field :firstname, placeholder: "Firstname", class: "input" %>
  </div>
  <div>
    <%= form.text_field :secondname, placeholder: "Secondname", class: "input" %>
  </div>
  <div>
    <%= form.text_field :email, placeholder: "Email", class: "input" %>
  </div>
  <div>
    <%= form.text_field :phone, placeholder: "Phone", class: "input" %>
  </div>
  <div>
    <%= form.text_field :twitter, placeholder: "Twitter" , class: "input" %>
  </div>
  <div class="btns">
    <div>
    <%= form.submit  class: "btn-editing-friend" %>
    </div>
    <div>
        <%= link_to "Back", root_path, class: "btn-new-back"%>
    </div>
  </div>
 
<% end %>

</div>

app/views/friends/edit.html.erb
<%= render partial: "friends/form_partial", locals: { friend: @friend } %>

app/views/friends/index.html.erb
    <div class="container">
        <div class="friends-card">
            <h3 class="friends-card-box-title"> First name </h3>
            <h3 class="friends-card-box-title"> Last name </h3>
            <h3 class="friends-card-box-title"> Email </h3>
            <h3 class="friends-card-box-title" > Phone </h3>
            <h3 class="friends-card-box-title"> Twitter </h3>
            <div class="friends-card-box-filledout"> </div>

        </div>   
    </div>

    

    <%@friend.each  do | friends | %>
    <div class="container">
        <div class="friends-card">
            <p class="friends-card-box"> <%= friends.firstname%> </p>
            <p class="friends-card-box"> <%= friends.secondname%> </p>
            <p class="friends-card-box"> <%= friends.email%> </p>
            <p class="friends-card-box"> <%= friends.phone%> </p>
            <p class="friends-card-box"> <%= friends.twitter%> </p>
            <%=  link_to 'Show', friend_path(friends),  class: 'friends-card-box link'  %>
            <%=  button_to 'Destroy', friends,  method: :delete, class: 'friends-card-box-destroy link' %>
            <%=  link_to 'Edit', edit_friend_path(friends), class: 'friends-card-box link'%>
        </div>   
    </div>   
    <% end %>

    <br>
    <div class="container-btn">
    <%= link_to 'New Friend', new_friend_path, class: "btn-new-friend"%>
    </div>

app/views/friends/new.html.erb
<%= render partial: "friends/form_partial", locals: { friend: @friend } %>

app/views/friends/show.html.erb
<div class="container-show">
    <div class="friend-card-show">
        <h1><%= @friend.firstname %></h1>
        <p><%= @friend.email %> • <%= @friend.phone %> • <%= @friend.twitter %><p> 
    </div>
    <div>
        <%= link_to "Back", root_path, class: "btn-new-back"%>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "List" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,300;0,400;1,500&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>